version: '3'
services:
  api:
    build: gdeep29/cafeapi

    ports:
      - 80:8000

    environment:
      - SECRET_KEY_API=${SECRET_KEY_API}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
