"""auto_generate_cafes_users_table

Revision ID: 8f96851ffe92
Revises: 
Create Date: 2023-06-01 10:52:28.523101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f96851ffe92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cafes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('can_take_calls', sa.Boolean(), nullable=False),
    sa.Column('coffee_price', sa.Float(), nullable=False),
    sa.Column('has_sockets', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('map_url', sa.String(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafes')
    op.drop_table('users')
    # ### end Alembic commands ###
